### ISSUE TITLE
Lung lesion analyzer run fail with Slicer5.x

### ISSUE THREAD

**Issue by phoenixsfly** [acil-bwh/SlicerCIP#42]
**environment:**
OS: Windows11
Slicer Ver: 5.2.1 stable release
CIP: install from slicer extension manager

I used this *lung lesion analyzer* in the [tutorial](https://chestimagingplatform.org/files/chestimagingplatform/files/lung_lesion_analyzer.pdf) to segmnet lung nodule.
I patched seed point and clicked "Segment nodule" button, the program ran for a while and displayed "**Status: Completed with errors**"
> Lesion Segmentation terminated with an unknown exception.

>Traceback (most recent call last):
  File "C:/Users/uu/AppData/Local/NA-MIC/Slicer 5.2.1/NA-MIC/Extensions-31317/Chest_Imaging_Platform/lib/Slicer-5.2/qt-scripted-modules/CIP_LesionModel.py", line 2181, in <lambda>
    result.AddObserver("ModifiedEvent", lambda caller, event: self.__onNoduleSegmentationCLIStateUpdated__(
  File "C:/Users/uu/AppData/Local/NA-MIC/Slicer 5.2.1/NA-MIC/Extensions-31317/Chest_Imaging_Platform/lib/Slicer-5.2/qt-scripted-modules/CIP_LesionModel.py", line 2420, in __onNoduleSegmentationCLIStateUpdated__
    raise Exception("The Nodule Segmentation CLI failed")
Exception: The Nodule Segmentation CLI failed

I have done the same things on Ubuntu, the task also failed with:
>Lesion Segmentation standard error:
terminate called after throwing an instance of 'slicer_itk::ExceptionObject'
  what():  /work/Stable/Slicer-0-build/ITK/Modules/Core/SpatialObjects/include/itkSpatialObjectPoint.hxx:59:
ITK ERROR: SpatialObjectPoint(0x1218f10): The SpatialObject must be set prior to calling.

>Traceback (most recent call last):
  File "/home/uu/Slicer-5.2.1-linux-amd64/NA-MIC/Extensions-31317/Chest_Imaging_Platform/lib/Slicer-5.2/qt-scripted-modules/CIP_LesionModel.py", line 2181, in <lambda>
    result.AddObserver("ModifiedEvent", lambda caller, event: self.__onNoduleSegmentationCLIStateUpdated__(
  File "/home/uu/Slicer-5.2.1-linux-amd64/NA-MIC/Extensions-31317/Chest_Imaging_Platform/lib/Slicer-5.2/qt-scripted-modules/CIP_LesionModel.py", line 2420, in __onNoduleSegmentationCLIStateUpdated__
    raise Exception("The Nodule Segmentation CLI failed")
Exception: The Nodule Segmentation CLI failed

I try to reinstall Slicer with 5.1.0 and 5.0.0, the the same issue occured
Finally, I download [SlicerCIP integrated](https://chestimagingplatform.org/download)(4.10.2), everything is OK.
**So I guess CIP is not compatible with Slicer5.x, right?**

**Comment by rbumm** [comment]
You are right - CIP lung lesion analyzer is currently not compatible with Slicer 5. 

We may take it out of the selection to leave only functional modules in there.

**Comment by rjosest** [comment]
Hello,Thank you for reporting this issue. We can look into this.If you are interested in this module, you could use the prebuilt SlicerCIP version that we support. You can download it from here:Downloadchestimagingplatform.orgThanksRaulOn Feb 17, 2023, at 12:46 AM, phoenixsfly ***@***.***> wrote:﻿
environment:
OS: Windows11
Slicer Ver: 5.2.1 stable release
CIP: install from slicer extension manager
I used this lung lesion analyzer in the tutorial to segmnet lung nodule.
I patched seed point and clicked "Segment nodule" button, the program ran for a while and displayed "Status: Completed with errors"

Lesion Segmentation terminated with an unknown exception.


Traceback (most recent call last):
File "C:/Users/uu/AppData/Local/NA-MIC/Slicer 5.2.1/NA-MIC/Extensions-31317/Chest_Imaging_Platform/lib/Slicer-5.2/qt-scripted-modules/CIP_LesionModel.py", line 2181, in 
result.AddObserver("ModifiedEvent", lambda caller, event: self.onNoduleSegmentationCLIStateUpdated(
File "C:/Users/uu/AppData/Local/NA-MIC/Slicer 5.2.1/NA-MIC/Extensions-31317/Chest_Imaging_Platform/lib/Slicer-5.2/qt-scripted-modules/CIP_LesionModel.py", line 2420, in onNoduleSegmentationCLIStateUpdated
raise Exception("The Nodule Segmentation CLI failed")
Exception: The Nodule Segmentation CLI failed

I have done the same things on Ubuntu, the task also failed with:

Lesion Segmentation standard error:
terminate called after throwing an instance of 'slicer_itk::ExceptionObject'
what():  /work/Stable/Slicer-0-build/ITK/Modules/Core/SpatialObjects/include/itkSpatialObjectPoint.hxx:59:
ITK ERROR: SpatialObjectPoint(0x1218f10): The SpatialObject must be set prior to calling.


Traceback (most recent call last):
File "/home/uu/Slicer-5.2.1-linux-amd64/NA-MIC/Extensions-31317/Chest_Imaging_Platform/lib/Slicer-5.2/qt-scripted-modules/CIP_LesionModel.py", line 2181, in 
result.AddObserver("ModifiedEvent", lambda caller, event: self.onNoduleSegmentationCLIStateUpdated(
File "/home/uu/Slicer-5.2.1-linux-amd64/NA-MIC/Extensions-31317/Chest_Imaging_Platform/lib/Slicer-5.2/qt-scripted-modules/CIP_LesionModel.py", line 2420, in onNoduleSegmentationCLIStateUpdated
raise Exception("The Nodule Segmentation CLI failed")
Exception: The Nodule Segmentation CLI failed

I try to reinstall Slicer with 5.1.0 and 5.0.0, the the same issue occured
Finally, I download SlicerCIP integrated(4.10.0), everything is OK.
So I guess CIP is not compatible with Slicer5.x, right?

**Comment by phoenixsfly** [comment]
> You are right - CIP lung lesion analyzer is currently not compatible with Slicer 5. 
> 
> We may take it out of the selection to leave only functional modules in there.

I see.... It is hoped that the nodule segmentation function will be preserved and compatible with the Slicer5 as soon.🫥
